### ISSUE TITLE
How to select a specific set of operators for the training

### ISSUE THREAD

**Issue by sambatra** [brendenpetersen/deep-symbolic-regression#12]
Hi there,

I have recently found this nice library for symbolic regression. Being used to sklearn interface, I was wondering whether it is possible to modify the config file (and how) such that only a few operators are chosen amongst the default set which includes everything. Using the default set gives me decent results for my regression problem, however the best expression contains exp and trig terms which I would like to avoid as much as possible as they make the results a bit harder to interpret.

Best,
Sam

**Comment by brendenpetersen** [comment]
Hi @sambatra,

You can explicitly set which operators you'd like to include in the `"function_set"` key of `config.json` under the `"task"` top-level key. For example:

```
"task": {
    "function_set" : ["add", "sub", "mul", "div"],
    ...
},
...
```

You can also include `"const"` as a token to if you'd like to include optimized floating-point constants, just keep in mind that this will slow the runtime down by a lot because it introduces an inner optimization loop.

> I would like to avoid as much as possible as they make the results a bit harder to interpret.

As an alternative, with DSR you can add limits to the _number of times_ a token can appear in a given expression. This allows you to still include trig/exp/log tokens, without letting them overwhelm the expression and become less interpretable. For example, you can limit each expression to having at most a total of 2 trig/exp/log terms by adjusting the config like this:

```
"task": {
    "function_set" : ["add", "sub", "mul", "div", "sin", "cos", "exp", "log"],
    ...
},
"prior" : {
    "repeat" : {"tokens" : ["exp", "log", "sin", "cos"], "max_" : 2},
    ...
    },
},
...
```

Let me know if this helps! Don't hesitate to reach out for anything else.

**Comment by sambatra** [comment]
Hi @brendenpetersen 

Many thanks for you help. I will experiment a bit.

**Comment by sambatra** [comment]
Hi @brendenpetersen 

It works pretty well, thanks!...I will try the alternative you suggested.

**Comment by brendenpetersen** [comment]
Wonderful! Stay tuned for an update to the code soon.
